name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download the build output
        uses: actions/download-artifact@v2
        with:
          name: dist
      - run: ls -la
      - run: echo "GELLO"
